// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmQPMDr9b39upLcgQmSekzt50EoZP8f-4',
    appId: '1:910240519772:web:95aa773ae218bf27fbb899',
    messagingSenderId: '910240519772',
    projectId: 'temparty-12538',
    authDomain: 'temparty-12538.firebaseapp.com',
    databaseURL: 'https://temparty-12538-default-rtdb.firebaseio.com',
    storageBucket: 'temparty-12538.appspot.com',
    measurementId: 'G-G0LS78BS93',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIZT7-mA8KizUa-pwXcwcXYbrKuoUaXU4',
    appId: '1:910240519772:android:fdeca7b342924e28fbb899',
    messagingSenderId: '910240519772',
    projectId: 'temparty-12538',
    databaseURL: 'https://temparty-12538-default-rtdb.firebaseio.com',
    storageBucket: 'temparty-12538.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmmzVha5U2WsQIKTzN_acqQPgDyGOCPwA',
    appId: '1:910240519772:ios:d5377b25fb93dd7bfbb899',
    messagingSenderId: '910240519772',
    projectId: 'temparty-12538',
    databaseURL: 'https://temparty-12538-default-rtdb.firebaseio.com',
    storageBucket: 'temparty-12538.appspot.com',
    iosClientId: '910240519772-ns6iqngpkpoebdd8b5i6sufjfnvgegs5.apps.googleusercontent.com',
    iosBundleId: 'com.example.tempartyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmmzVha5U2WsQIKTzN_acqQPgDyGOCPwA',
    appId: '1:910240519772:ios:d5377b25fb93dd7bfbb899',
    messagingSenderId: '910240519772',
    projectId: 'temparty-12538',
    databaseURL: 'https://temparty-12538-default-rtdb.firebaseio.com',
    storageBucket: 'temparty-12538.appspot.com',
    iosClientId: '910240519772-ns6iqngpkpoebdd8b5i6sufjfnvgegs5.apps.googleusercontent.com',
    iosBundleId: 'com.example.tempartyApp',
  );
}
